#!/bin/bash

# Get the aliases and functions
# [ -f $HOME/.bashrc ] && . $HOME/.bashrc

source ~/.config/bash/bashrc
source ~/.config/bash/bash_aliases

export HISTFILE="${XDG_CONFIG_HOME}"/bash/history