#!/bin/bash
#   	 _ _
#   __ _| (_) __ _ ___  ___  ___
#  / _` | | |/ _` / __|/ _ \/ __|
# | (_| | | | (_| \__ \  __/\__ \
#  \__,_|_|_|\__,_|___/\___||___/


# shell commands
# alias ls='ls --color=auto'
# alias la="ls -a"
# alias ll="ls -l"
alias ls='exa'
alias la="exa -la"
alias mv="mv -v"  
alias rm="rm -v"
alias ll="exa -l"
alias bat="bat --color=always --style=plain "
alias cat="bat"
alias cls=clear
alias f3d="swallow f3d & disown"
alias x="exit"
alias doas="doas "
# i3 
alias i3conf="micro ~/.config/i3/config"
alias i3bconf="micro ~/.config/i3blocks/config"
alias lf=lfrun
# text editors  
alias p="python3.12"
alias s="subl4"
alias m="micro"
alias v="vim"
alias nv="nvim"
alias lv="lvim" 
alias r="ranger"
alias z="swallow zathura "
alias sk="swallow sioyek "
alias discord="swallow ~/pkgs/discord/Discord & disown"
#scripts 
alias sb="~/.scripts/statusbar"
# Latex
alias tlmgr="doas tlmgr "
# xbps 
alias xu='doas xbps-install -u xbps -y ; doas xbps-install -Suv'       # update packages 
alias xi='doas xbps-install'            # install package 
alias xr='doas xbps-remove -Rcon'       # remove cache, dependencies and orphans 
alias xfr='doas xbps-remove -Rcon -fF'  # force remove package 
alias xl='xbps-query -l'                # list all installed packages 
alias xf='xl | grep '                   # search in installed packages
alias xs='xbps-query -Rs'               # query package in repos  
alias xd='xbps-query -x'                # query package dependencies
alias xrd='xbps-query -X'               # query package reverse dependencies    

# session management
alias reboot="doas reboot"
alias halt='doas halt'
alias shutdown='doas shutdown'
alias poweroff='doas poweroff'
alias zzz='doas zzz'

alias conservation="doas sh ~/scripts/conservation"
alias blog="cd ~/Documents/blog/blog-source-code" 
alias pro="cd ~/Documents/projects/"

alias movies="cd /mnt/Data/movies-and-series"
alias todo="sh ~/scripts/todo"

alias asmarine="xhost + ; distrobox enter asmarine"

## FUNCTIONS 
clean(){
	  doas xbps-remove -o # remove unneeded orphan pkgs
	  doas xbps-remove -O # remove obsolete cache
	  doas vkpurge rm all # remove old kernels and drivers
}

rmd(){ 
    Rscript -e "rmarkdown::render('$1')" 
}

get_pass(){
    pass "$1" | xclip -selection clipboard 
}

gen_pass(){
  pwgen -By 30 1 | xclip -selection clipboard
}

change_mac(){
    doas ifconfig wlp4s0 down
    doas macchanger -r wlp4s0
    doas ifconfig wlp4s0 up 
}

marktext(){
    swallow ~/pkgs/marktext.AppImage "$@" & disown >/dev/null 
}


